

UPDATE cliente
SET nome = 'MARIA RAIMUNDA'
WHERE id = 4; -- MUDAR DADOS NA TABELA

SELECT REPLACE('ANDREI JOSE', 'JOSE','VERCOSA'); -- TESTAR MODIFICAÇÃO

SELECT * FROM cliente; -- MOSTRAR TABELA 

UPDATE cliente
SET nome = REPLACE(nome,'JOSE','VERCOSA')
WHERE id = 1; -- MUDAR DADOS NA TABELA