
ALTER TABLE cliente MODIFY nome VARCHAR(50); -- ALTERAR TABELA

SELECT * FROM cliente; -- MOSTRAR TABELA 

INSERT INTO cliente(nome)
VALUES('ANDREI JOSE'),
('LUIZ ALGUSTO'), ('ANTONIO JOSE'), ('MARIA RITA'),('VALERIA DUARTE'); -- INSERT MAIS DE UM DADO

DESC cliente; -- DESCRIÇÃO DA TABELA

CREATE TABLE cliente(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(5),
dtVadastro DATETIME DEFAULT CURRENT_TIMESTAMP()
) -- CRIAR TABELA
